---

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/application/backend"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/application/frontend"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
